-- MERGE INTO temp_hibah_lengkap AS t
-- USING (
--     SELECT
--         h.id,
--         h.skema,
--         h.sdgs,
--         -- Original value is valid
--         sm.skema AS skema_match,
--         dm.sdgs AS sdgs_match,
--         -- Cross lookup (used to detect swapped values)
--         sm2.skema AS sdgs_in_skema,
--         dm2.sdgs AS skema_in_sdgs

--     FROM hibah_lengkap h
--     LEFT JOIN lookup_skema sm
--         ON LOWER(TRIM(h.skema)) = LOWER(TRIM(sm.skema))
--     LEFT JOIN lookup_sdgs dm
--         ON LOWER(TRIM(h.sdgs)) = LOWER(TRIM(dm.sdgs))
--     LEFT JOIN lookup_skema sm2
--         ON LOWER(TRIM(h.sdgs)) = LOWER(TRIM(sm2.skema))
--     LEFT JOIN lookup_sdgs dm2
--         ON LOWER(TRIM(h.skema)) = LOWER(TRIM(dm2.sdgs))

-- ) AS s

-- ON t.id = s.id
-- -- Case 1 : Both values are swapped
-- -- skema = SDGS
-- -- sdgs = SKEMA
-- WHEN MATCHED
--     AND s.skema_match IS NULL
--     AND s.sdgs_match IS NULL
--     AND s.skema_in_sdgs IS NOT NULL
--     AND s.sdgs_in_skema IS NOT NULL
-- THEN
-- UPDATE SET
--     skema = s.sdgs,
--     sdgs = s.skema
-- -- Case 2 : skema is NULL/invalid
-- -- skema = NULL
-- -- sdgs  = SKEMA
-- -- Move sdgs -> skema
-- WHEN MATCHED
--     AND s.sdgs_in_skema IS NOT NULL
--     AND s.skema_in_sdgs IS NULL
-- THEN
-- UPDATE SET
--     skema = s.sdgs,
--     sdgs = NULL
-- -- Case 3 : sdgs is NULL/invalid
-- -- skema = SDGS
-- -- sdgs  = NULL
-- -- Move skema -> sdgs
-- WHEN MATCHED
--     AND s.skema_in_sdgs IS NOT NULL
--     AND s.sdgs_in_skema IS NULL
-- THEN
-- UPDATE SET
--     skema = NULL,
--     sdgs = s.skema
